# -*- coding: utf-8 -*-
#
# 行人跌倒检测系统 —— PyQt5 界面定义（由 untitled.ui 通过 pyuic5 生成）
# Copyright (C) 2026 SiyuChen12138
# 本文件以 GNU General Public License v3.0 发布，完整许可文本见 LICENSE。
# PyQt5 本身以 GPL-3.0 / 商业许可 双许可发布，见 https://riverbankcomputing.com/software/pyqt/
#
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1327, 825)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenVideoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenVideoBtn.setGeometry(QtCore.QRect(280, 510, 211, 51))
        self.OpenVideoBtn.setObjectName("OpenVideoBtn")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1301, 481))
        self.groupBox.setObjectName("groupBox")
        self.Imglabel = QtWidgets.QLabel(self.groupBox)
        self.Imglabel.setGeometry(QtCore.QRect(340, 10, 641, 451))
        self.Imglabel.setText("")
        self.Imglabel.setObjectName("Imglabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 570, 1291, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Infolabel = QtWidgets.QLabel(self.groupBox_2)
        self.Infolabel.setGeometry(QtCore.QRect(30, 50, 1221, 121))
        self.Infolabel.setText("")
        self.Infolabel.setObjectName("Infolabel")
        self.CameraBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CameraBtn.setGeometry(QtCore.QRect(870, 510, 211, 51))
        self.CameraBtn.setObjectName("CameraBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenVideoBtn.setText(_translate("MainWindow", "视频/图片输入"))
        self.groupBox.setTitle(_translate("MainWindow", "处理结果"))
        self.groupBox_2.setTitle(_translate("MainWindow", "详细信息"))
        self.CameraBtn.setText(_translate("MainWindow", "启用摄像头"))
